name: pascapanen_mobile
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.15
  collection: ^1.17.1
  http: ^1.3.0
  path: ^1.8.3
  sqflite_common_ffi: ^2.0.0
  sqflite: ^2.0.0+3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6

 
  flutter_lints: ^5.0.0


flutter:

  
  uses-material-design: true

  assets:
    - assets/logoapk.png
    - assets/logogoogle.webp
    - assets/logo_splash.png
    - assets/logo_splash1.png
    - assets/logo_splash2.jpg
    - assets/logo_splash3.jpg
    - assets/berita1.jpg
    - assets/berita2.jpg
    - assets/berita3.jpg


  