name: pascapanen_mobile
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  permission_handler: ^11.3.0
  url_launcher: ^6.2.5
  geolocator: ^11.0.0
  geocoding: ^2.1.0
  dio: ^5.4.0
  image_picker: ^1.0.7
  marquee: ^2.2.3
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.15
  collection: ^1.17.1
  http: ^1.3.0
  path: ^1.8.3
  sqflite_common_ffi: ^2.0.0
  sqflite: ^2.0.0+3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6

  flutter_lints: ^5.0.0

flutter:

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300

  uses-material-design: true
  assets:
    - assets/logoapk.png
    - assets/logogoogle.webp
    - assets/logo_splash.png
    - assets/logo_splash1.png
    - assets/logo_splash2.jpg
    - assets/logo_splash3.jpg
    - assets/berita1.jpg
    - assets/berita2.jpg
    - assets/berita3.jpg
    - assets/beras1.jpg
    - assets/beras2.jpg
    - assets/pupuk.jpg
    - assets/obat.jpg
    - assets/background_pattern.png